#!/bin/bash

echo "UCMR5 Water Quality API Setup"
echo "=============================="
echo ""
echo "This project requires the UCMR5_All.txt data file (234MB)."
echo ""
echo "Due to its size, you have two options:"
echo ""
echo "1. Download directly from EPA:"
echo "   https://www.epa.gov/dwucmr/occurrence-data-unregulated-contaminant-monitoring-rule"
echo "   Download 'UCMR5_All.txt' and place it in this directory"
echo ""
echo "2. Use Git LFS (if you have bandwidth):"
echo "   git lfs pull"
echo ""
echo "After obtaining the data file, run:"
echo "   npm install"
echo "   npm run build"
echo ""
echo "This will create the SQLite database for the API."